package tseg.janelas;

import java.awt.Color;
import java.awt.event.ActionEvent;
import tseg.acoes.AcaoJanelaPrincipal;
import tseg.controle.Controle;

public class LegendaCores extends javax.swing.JPanel {

    public LegendaCores() {
        initComponents();
        
        acao = new AcaoJanelaPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        txtUnidade = new javax.swing.JTextField();
        txtUnidadeIntercalada = new javax.swing.JTextField();
        txtUnidadeEmbutida = new javax.swing.JTextField();
        txtSegmentoSobreposto = new javax.swing.JTextField();
        txtUnidadeIndependente = new javax.swing.JTextField();
        labelUnidade = new javax.swing.JLabel();
        labelUnidadeIntercalada = new javax.swing.JLabel();
        labelUnidadeEmbutida = new javax.swing.JLabel();
        labelSegmentoSobreposto = new javax.swing.JLabel();
        labelUnidadeIndependente = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        txtUnidade.setEditable(false);
        txtUnidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnidadeMouseClicked(evt);
            }
        });

        txtUnidadeIntercalada.setEditable(false);
        txtUnidadeIntercalada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUnidadeIntercalada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnidadeIntercaladaMouseClicked(evt);
            }
        });

        txtUnidadeEmbutida.setEditable(false);
        txtUnidadeEmbutida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUnidadeEmbutida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnidadeEmbutidaMouseClicked(evt);
            }
        });

        txtSegmentoSobreposto.setEditable(false);
        txtSegmentoSobreposto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSegmentoSobreposto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSegmentoSobrepostoMouseClicked(evt);
            }
        });

        txtUnidadeIndependente.setEditable(false);
        txtUnidadeIndependente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUnidadeIndependente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUnidadeIndependenteMouseClicked(evt);
            }
        });

        labelUnidade.setText("Unidade");
        labelUnidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUnidadeMouseClicked(evt);
            }
        });

        labelUnidadeIntercalada.setText("Unidade (intercalada)");
        labelUnidadeIntercalada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelUnidadeIntercalada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUnidadeIntercaladaMouseClicked(evt);
            }
        });

        labelUnidadeEmbutida.setText("Unidade embutida");
        labelUnidadeEmbutida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelUnidadeEmbutida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUnidadeEmbutidaMouseClicked(evt);
            }
        });

        labelSegmentoSobreposto.setText("Segmento sobreposto");
        labelSegmentoSobreposto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelSegmentoSobreposto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSegmentoSobrepostoMouseClicked(evt);
            }
        });

        labelUnidadeIndependente.setText("Unidade Independente");
        labelUnidadeIndependente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelUnidadeIndependente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUnidadeIndependenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidadeIntercalada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUnidadeIntercalada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidadeEmbutida, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUnidadeEmbutida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSegmentoSobreposto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSegmentoSobreposto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidadeIndependente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUnidadeIndependente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnidade)
                    .addComponent(txtUnidadeIntercalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnidadeIntercalada)
                    .addComponent(txtUnidadeEmbutida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnidadeEmbutida)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSegmentoSobreposto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSegmentoSobreposto)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUnidadeIndependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUnidadeIndependente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadeMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidades().actionPerformed(null);
    }//GEN-LAST:event_txtUnidadeMouseClicked

    private void txtUnidadeIntercaladaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadeIntercaladaMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidades2().actionPerformed(null);
    }//GEN-LAST:event_txtUnidadeIntercaladaMouseClicked

    private void txtUnidadeEmbutidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadeEmbutidaMouseClicked
        // TODO add your handling code here
        acao.itemCorUnidadesEmbutidas().actionPerformed(null);
    }//GEN-LAST:event_txtUnidadeEmbutidaMouseClicked

    private void txtSegmentoSobrepostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSegmentoSobrepostoMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidadesSobrepostas().actionPerformed(null);
    }//GEN-LAST:event_txtSegmentoSobrepostoMouseClicked

    private void txtUnidadeIndependenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUnidadeIndependenteMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidadesIndependentes().actionPerformed(null);
    }//GEN-LAST:event_txtUnidadeIndependenteMouseClicked

    private void labelUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUnidadeMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidades().actionPerformed(null);
    }//GEN-LAST:event_labelUnidadeMouseClicked

    private void labelUnidadeIntercaladaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUnidadeIntercaladaMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidades2().actionPerformed(null);
    }//GEN-LAST:event_labelUnidadeIntercaladaMouseClicked

    private void labelUnidadeEmbutidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUnidadeEmbutidaMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidadesEmbutidas().actionPerformed(null);
    }//GEN-LAST:event_labelUnidadeEmbutidaMouseClicked

    private void labelSegmentoSobrepostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSegmentoSobrepostoMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidadesSobrepostas().actionPerformed(null);
    }//GEN-LAST:event_labelSegmentoSobrepostoMouseClicked

    private void labelUnidadeIndependenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUnidadeIndependenteMouseClicked
        // TODO add your handling code here:
        acao.itemCorUnidadesIndependentes().actionPerformed(null);
    }//GEN-LAST:event_labelUnidadeIndependenteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel labelSegmentoSobreposto;
    private javax.swing.JLabel labelUnidade;
    private javax.swing.JLabel labelUnidadeEmbutida;
    private javax.swing.JLabel labelUnidadeIndependente;
    private javax.swing.JLabel labelUnidadeIntercalada;
    private javax.swing.JTextField txtSegmentoSobreposto;
    private javax.swing.JTextField txtUnidade;
    private javax.swing.JTextField txtUnidadeEmbutida;
    private javax.swing.JTextField txtUnidadeIndependente;
    private javax.swing.JTextField txtUnidadeIntercalada;
    // End of variables declaration//GEN-END:variables
    private AcaoJanelaPrincipal acao;
    
    public void translateDescr(boolean portugues)
    {
        if(!portugues)
        {
            labelUnidade.setText("Unit");
            labelUnidadeIntercalada.setText("Interleaved unit");
            labelUnidadeEmbutida.setText("Built-in unit");
            labelSegmentoSobreposto.setText("Overlapping segment");
            labelUnidadeIndependente.setText("Independent unit");
        }
        else
        {
            labelUnidade.setText("Unidade");
            labelUnidadeIntercalada.setText("Unidade (intercalada)");
            labelUnidadeEmbutida.setText("Unidade embutida");
            labelSegmentoSobreposto.setText("Segmento sobreposto");
            labelUnidadeIndependente.setText("Unidade independente");
        }
    }
    
    public void setCorUnidade(Color bgColor)
    {
        txtUnidade.setBackground(bgColor);
    }
    
    public void setCorUnidadeIntercalada(Color bgColor)
    {
        txtUnidadeIntercalada.setBackground(bgColor);
    }
        
    public void setCorUnidadeEmbutida(Color bgColor)
    {
        txtUnidadeEmbutida.setBackground(bgColor);
    }
            
    public void setCorSegmentoSobreposto(Color bgColor)
    {
        txtSegmentoSobreposto.setBackground(bgColor);
    }
                
    public void setCorUnidadeIndependente(Color bgColor)
    {
        txtUnidadeIndependente.setBackground(bgColor);
    }
}
