/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tseg.janelas;

import java.awt.Desktop;
import java.net.URI;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author ctcca
 */
public class ModalSobre extends javax.swing.JDialog {

    /**
     * Creates new form ModalSobre
     */
    public ModalSobre(boolean portugues) {
        initComponents();
        
        StyledDocument doc = TextPaneSobre.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_JUSTIFIED);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);
        
        //Coisas feitas por fora
        setModal(true);
        setLocationRelativeTo(null);
        translateDescr(portugues);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLogotipo = new javax.swing.JLabel();
        LabelVersao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextPaneSobre = new javax.swing.JTextPane();
        LabelMaisInfo = new javax.swing.JLabel();
        LabelLink = new javax.swing.JLabel();

        setTitle("Sobre o T-Seg");
        setResizable(false);

        LabelLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/T-Seg.png"))); // NOI18N

        LabelVersao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelVersao.setText("Versão 1.01");

        TextPaneSobre.setEditable(false);
        TextPaneSobre.setBackground(new java.awt.Color(240, 240, 240));
        TextPaneSobre.setText("T-Seg é uma ferramenta para marcação e segmentação de textos usada para definição de unidades mínimas de anotação de corpora. Nele, o usuário define como quer que seja feita automaticamente a segmentação (por meio de regras), podendo inclusive marcar manualmente os segmentos em um texto-fonte. Caso a marcaçao seja feita manualmente, vários usuários podem executar a mesma tarefa, cabendo então ao sistema determinar o nível de confiança do esquema de marcação utilizado, com base em uma análise do grau de concordância entre os marcadores humanos.");
        TextPaneSobre.setAutoscrolls(false);
        jScrollPane2.setViewportView(TextPaneSobre);

        LabelMaisInfo.setText("Mais informações em:");

        LabelLink.setText("<html><a href=\"#\">http://www.each.usp.br/norton/resdial/</a></html>");
        LabelLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(LabelLogotipo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(LabelVersao)))
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LabelMaisInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelLogotipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelVersao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelMaisInfo)
                    .addComponent(LabelLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLinkMouseClicked
        // TODO add your handling code here:
        try
        {
            Desktop.getDesktop().browse(new URI("http://www.each.usp.br/norton/resdial/"));
        }
        catch(Exception e)
        {
            //Se o link não for aberto esta excecao nao sera tratada
        }
    }//GEN-LAST:event_LabelLinkMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLink;
    private javax.swing.JLabel LabelLogotipo;
    private javax.swing.JLabel LabelMaisInfo;
    private javax.swing.JLabel LabelVersao;
    private javax.swing.JTextPane TextPaneSobre;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

private void translateDescr(boolean portugues)
{
    if(!portugues)
    {
        setTitle("About T-Seg");
        TextPaneSobre.setText("T-Seg is a tool for labeling and segmentation of texts used for defining minimum units of annotation corpora. In it, you define how you want to be automatically segmenting (by rules), and may also manually mark the segments in one source text. If the marking is done manually, multiple users can perform the same task, then fitting the system to determine the confidence level marking scheme used, based on an analysis the degree of agreement between human markers.");
        LabelVersao.setText("Version: 1.01");
        LabelMaisInfo.setText("For more information:");
    }
}
}
